version: '2'
services:
  api:
    build: ./
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      ELASTICSEARCH_HOST: 'elasticsearch'
      ELASTICSEARCH_PORT: 9200
    links:
      - redis
      - elasticsearch
    ports:
      - 9292:9292

  redis:
    image: redis
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
